Repository ie3-institute/simona, pull requests merged in 2022-10, with the labels that each got.

#355 Adapting jitpack url
  build.gradle
Labels: bug

#323 Enhancing DBFS tests with checking result outputs via listeners.
  CHANGELOG.md
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmCenGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmFailedPowerFlowSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSMockGridAgents.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/DbfsTestGrid.scala
Labels: test, dbfs

#377 Adapting to changed EvcsInput
  CHANGELOG.md
  input/samples/vn_simona/fullGrid/evcs_input.csv
  src/test/scala/edu/ie3/simona/test/common/input/EvcsInputTestData.scala
Labels: bug, dependencies

#385 Fix name and protocol changes within simonaAPI
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/EvMessage.scala
  src/main/scala/edu/ie3/simona/service/ExtDataSupport.scala
  src/main/scala/edu/ie3/simona/service/ev/ExtEvDataService.scala
  src/test/scala/edu/ie3/simona/agent/participant/EvcsAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/service/ev/ExtEvDataServiceSpec.scala
Labels: dependencies
