Repository ie3-institute/simona, pull requests merged in 2022-03, with the labels that each got.

#77 Let participant agent die on failed registration
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
Labels: bug

#154 fix variable height to elevationAngle
  input/samples/vn_simona/fullGrid/pv_input.csv
  src/main/scala/edu/ie3/simona/model/participant/PVModel.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceProxy.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSource.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSourceWrapper.scala
  src/test/groovy/edu/ie3/simona/model/participant/PVModelIT.groovy
  src/test/groovy/edu/ie3/simona/model/participant/PVModelTest.groovy
  src/test/resources/edu/ie3/simona/model/participant/pv/it/grid_data/pv_input.csv
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/PvInputTestData.scala
Labels: enhancement, dependencies

#161 Powerflow isn't converging troubleshooting
  docs/readthedocs/usersguide.rst
Labels: documentation

#98 Introducing primary data from SQL
  CHANGELOG.md
  build.gradle
  gradle/scripts/tscfg.gradle
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceProxy.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSourceWrapper.scala
  src/main/scala/edu/ie3/simona/util/ConfigUtil.scala
  src/test/resources/edu/ie3/simona/service/primary/timeseries/time_series_p.sql
  src/test/resources/edu/ie3/simona/service/primary/timeseries/time_series_pqh.sql
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSqlIT.scala
  src/test/scala/edu/ie3/simona/test/common/input/TimeSeriesTestData.scala
  src/test/scala/edu/ie3/simona/test/helper/TestContainerHelper.scala
Labels: enhancement

#171 Fix unreachable code
  src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala
Labels: bug, good first issue
