Repository ie3-institute/simona, pull requests merged in 2022-04, with the labels that each got.

#155 Change transformer calculation
  input/samples/vn_146_lv_small/fullGrid/transformer_2_w_type_input.csv
  input/samples/vn_simona/fullGrid/transformer_2_w_type_input.csv
  src/main/scala/edu/ie3/simona/model/grid/Transformer3wModel.scala
  src/main/scala/edu/ie3/simona/model/grid/TransformerModel.scala
  src/test/scala/edu/ie3/simona/test/common/ThreeWindingTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/Transformer3wTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/TransformerInputTestData.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/DbfsTestGrid.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/TransformerTestGrid.scala
Labels: enhancement, dependencies

#79 Adapt default resolution of weather source
  CHANGELOG.md
  docs/uml/main/ParticipantModelling.puml
  src/main/scala/edu/ie3/simona/agent/participant/pv/PVAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/WeatherMessage.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSource.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSourceWrapper.scala
  src/main/scala/edu/ie3/util/scala/DoubleUtils.scala
  src/test/groovy/edu/ie3/simona/model/participant/PVModelIT.groovy
  src/test/scala/edu/ie3/simona/agent/participant/PVAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/service/weather/SampleWeatherSourceSpec.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherSourceWrapperSpec.scala
Labels: enhancement

#131 Fix config auto-generation
  gradle/scripts/tscfg.gradle
  input/samples/vn_146_lv_small/vn_146_lv_small.conf
  input/samples/vn_simona/vn_simona.conf
  src/main/scala/edu/ie3/simona/config/ConfigConventions.scala
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/config/RefSystemParser.scala
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/config/VoltLvlParser.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/config/RefSystemParserSpec.scala
Labels: bug

#147 Update Missing Models
  docs/readthedocs/Makefile
  docs/readthedocs/_static/bib/references.bib
  docs/readthedocs/_static/figures/models/bm_model/bm_behaviour.png
  docs/readthedocs/_static/figures/models/bm_model/bm_parameters.png
  docs/readthedocs/_static/figures/models/bm_model/mc.png
  docs/readthedocs/_static/figures/models/chp_model/ChpModelCalculation.png
  docs/readthedocs/_static/figures/models/chp_model/ChpModelMathematicalNotations.png
  docs/readthedocs/_static/figures/models/chp_model/ModelChpModelCalculationConcept.png
  docs/readthedocs/_static/figures/models/chp_model/chp4.png
  docs/readthedocs/_static/figures/models/pv_model/ModelPv.png
  docs/readthedocs/_static/figures/models/transformer_model/ModelTwt.png
  docs/readthedocs/_static/figures/models/transformer_model/tecdoc_tc1.jpg
  docs/readthedocs/_static/figures/models/wec_model/EnerconE82cpPlot.png
  docs/readthedocs/_static/figures/models/wec_model/WecModelCalculation.png
  docs/readthedocs/about.md
  docs/readthedocs/conf.py
  docs/readthedocs/config/config.rst
  docs/readthedocs/config/runtime/participant/load.rst
  docs/readthedocs/developersguide.md
  docs/readthedocs/index.rst
  docs/readthedocs/make.bat
  docs/readthedocs/models/bm_model.md
  docs/readthedocs/models/chp_model.md
  docs/readthedocs/models/chp_model.rst
  docs/readthedocs/models/cts_model.md
  docs/readthedocs/models/evcs_model.md
  docs/readthedocs/models/evcs_model.rst
  docs/readthedocs/models/line_model.md
  docs/readthedocs/models/load_model.md
  docs/readthedocs/models/models.rst
  docs/readthedocs/models/pv_model.md
  docs/readthedocs/models/switch_model.md
  docs/readthedocs/models/three_winding_transformer_model.md
  docs/readthedocs/models/two_winding_transformer_model.md
  docs/readthedocs/models/wec_model.md
  docs/readthedocs/models/wec_model.rst
  docs/readthedocs/protocols.md
  docs/readthedocs/protocols.rst
  docs/readthedocs/requirements.txt
  docs/uml/main/models/pv_model/BehaviourPvModel.puml
Labels: documentation, good first issue

#194 Removing workaround for tscfg
  gradle/scripts/tscfg.gradle
Labels: dependencies

#198 Update gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#215 Update sphinx
  docs/readthedocs/requirements.txt
Labels: documentation, dependencies
