Repository ie3-institute/simona, pull requests merged in 2022-06, with the labels that each got.

#247 Updating reviewers in dependabot config
  .github/dependabot.yml
Labels: dependencies

#257 Df/#255 fix name loadprofile and update readme
  CHANGELOG.md
  README.md
  input/samples/vn_simona/fullGrid/load_input.csv
  src/main/scala/edu/ie3/simona/model/participant/load/profile/LoadProfileKey.scala
  src/main/scala/edu/ie3/simona/model/participant/load/profile/LoadProfileStore.scala
  src/main/scala/edu/ie3/simona/model/participant/load/profile/ProfileLoadModel.scala
  src/test/groovy/edu/ie3/simona/model/participant/load/FixedLoadModelTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/load/ProfileLoadModelTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/load/RandomLoadModelTest.groovy
  src/test/scala/edu/ie3/simona/integration/common/IntegrationSpecCommon.scala
  src/test/scala/edu/ie3/simona/model/participant/load/LoadModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/load/LoadProfileStoreSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/LoadInputTestData.scala
Labels: bug, documentation, dependencies

#29 Kafka `ResultEventListener` sink
  CHANGELOG.md
  Dockerfile
  build.gradle
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala
  src/main/scala/edu/ie3/simona/io/result/ResultEntityCsvSink.scala
  src/main/scala/edu/ie3/simona/io/result/ResultEntityKafkaSink.scala
  src/main/scala/edu/ie3/simona/io/result/ResultSinkType.scala
  src/main/scala/edu/ie3/simona/io/result/plain/PlainResult.scala
  src/main/scala/edu/ie3/simona/io/result/plain/PlainWriter.scala
  src/main/scala/edu/ie3/simona/model/participant/load/profile/LoadProfileKey.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/main/scala/edu/ie3/simona/util/ConfigUtil.scala
  src/main/scala/edu/ie3/simona/util/ResultFileHierarchy.scala
  src/main/scala/edu/ie3/util/scala/io/ScalaReflectionSerde.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala
  src/test/scala/edu/ie3/simona/io/result/ResultEntityKafkaSpec.scala
  src/test/scala/edu/ie3/simona/io/result/ResultSinkTypeSpec.scala
  src/test/scala/edu/ie3/simona/io/result/plain/PlainWriterSpec.scala
  src/test/scala/edu/ie3/simona/test/KafkaSpecLike.scala
Labels: enhancement
