Repository ie3-institute/simona, pull requests merged in 2022-07, with the labels that each got.

#266 Applying a lot of code improvements to DBFS algo & surrounding classes
  CHANGELOG.md
  input/samples/vn_simona/vn_simona.conf
  src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridResultsSupport.scala
  src/main/scala/edu/ie3/simona/agent/grid/PowerFlowSupport.scala
  src/main/scala/edu/ie3/simona/agent/grid/ReceivedValues.scala
  src/main/scala/edu/ie3/simona/agent/grid/ReceivedValuesStore.scala
  src/test/scala/edu/ie3/simona/agent/grid/ReceivedValuesStoreSpec.scala
Labels: code quality

#291 Remove workaround for spotless google-java-format
  gradle.properties
Labels: dependencies

#295 Fix test due to change of PU in p.u. within PSU
  CHANGELOG.md
  src/test/scala/edu/ie3/simona/model/assets/control/QControlSpec.scala
Labels: bug, dependencies

#71 Respect for slack voltage angle in distributed power flow calculation
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
  src/main/scala/edu/ie3/simona/agent/grid/PowerFlowSupport.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmCenGridSpec.scala
Labels: bug

#297 Adapting to refactorings relating to time series
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceProxy.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSourceWrapper.scala
  src/test/scala/edu/ie3/simona/service/ev/ExtEvDataServiceSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/TimeSeriesTestData.scala
Labels: dependencies

#274 Simplifying ParticipantConfigUtil
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/util/ConfigUtil.scala
  src/test/scala/edu/ie3/simona/agent/participant/FixedFeedInAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentFixedModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentProfileModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/PVAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/WecAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/FixedFeedInModelSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/EvcsInputTestData.scala
  src/test/scala/edu/ie3/simona/util/ConfigUtilsSpec.scala
Labels: code quality
