Repository ie3-institute/simona, pull requests merged in 2022-05, with the labels that each got.

#220 Changing the export methode for diagrams.
  docs/readthedocs/models/chp_model.md
  docs/readthedocs/models/wec_model.md
Labels: documentation

#80 Implement termination message for external simulation
  CHANGELOG.md
  docs/readthedocs/usersguide.rst
  docs/uml/protocol/ExtEvSimulationSequence.puml
  src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
  src/main/scala/edu/ie3/simona/agent/state/AgentState.scala
  src/main/scala/edu/ie3/simona/api/ExtSimAdapter.scala
  src/main/scala/edu/ie3/simona/ontology/messages/StopMessage.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimLoader.scala
  src/main/sh/deploy/init-run.sh
  src/test/scala/edu/ie3/simona/api/ExtSimAdapterSpec.scala
Labels: enhancement

#213 Some code improvements in `RefSystemParser`
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/config/RefSystemParser.scala
  src/test/scala/edu/ie3/simona/config/RefSystemParserSpec.scala
Labels: improvement

#230 Remove gradle task for uml diagram export puml2png
  CHANGELOG.md
  gradle/scripts/documentation.gradle
Labels: documentation

#150 Consolidate csv parameterization
  CHANGELOG.md
  input/samples/vn_146_lv_small/vn_146_lv_small.conf
  input/samples/vn_simona/vn_simona.conf
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/io/grid/GridProvider.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceProxy.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSource.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSourceWrapper.scala
  src/main/scala/edu/ie3/simona/util/ConfigUtil.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/io/result/ResultSinkTypeSpec.scala
  src/test/scala/edu/ie3/simona/scheduler/SimSchedulerSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySpec.scala
  src/test/scala/edu/ie3/simona/test/common/ConfigTestData.scala
Labels: improvement

#200 Implementing a new plugin framework.
  docs/readthedocs/usersguide.md
  docs/readthedocs/usersguide.rst
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimLoader.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/resources/edu/ie3/simona/sim/setup/ext-sim-loader/jars/mock_ext_sim-2.jar
  src/test/resources/edu/ie3/simona/sim/setup/ext-sim-loader/jars/mock_ext_sim-empty_file.jar
  src/test/resources/edu/ie3/simona/sim/setup/ext-sim-loader/jars/mock_ext_sim-missing_extlink.jar
  src/test/resources/edu/ie3/simona/sim/setup/ext-sim-loader/jars/mock_ext_sim-missing_service_file.jar
  src/test/resources/edu/ie3/simona/sim/setup/ext-sim-loader/jars/mock_ext_sim-two_implementations.jar
  src/test/resources/edu/ie3/simona/sim/setup/ext-sim-loader/jars/mock_ext_sim-wrong_extlink.jar
  src/test/resources/edu/ie3/simona/sim/setup/ext-sim-loader/jars/mock_ext_sim-wrong_implementation.jar
  src/test/scala/edu/ie3/simona/sim/setup/ExtSimLoaderSpec.scala
Labels: improvement

#236 Removing RocketChat from Jenkinsfile
  Jenkinsfile
Labels: ci

#244 Updating PowerSystemUtils to 2.0-SNAPSHOT
  CHANGELOG.md
  build.gradle
  src/test/scala/edu/ie3/simona/service/weather/WeatherSourceSpec.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherSourceWrapperSpec.scala
Labels: bug, dependencies

#240 Update Changelog
  CHANGELOG.md
Labels: documentation
