Repository ie3-institute/simona, pull requests merged in 2022-08, with the labels that each got.

#286 Consolidate and enhance SimScheduler tests
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/scheduler/SimScheduler.scala
  src/test/scala/edu/ie3/simona/scheduler/ExtendedSimSchedulerSpec.scala
  src/test/scala/edu/ie3/simona/scheduler/SimSchedulerSpec.scala
Labels: test

#25 DBFS with multiple connections between sub grids
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentDataHelper.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridEnvironment.scala
  src/main/scala/edu/ie3/simona/agent/grid/PowerFlowSupport.scala
  src/main/scala/edu/ie3/simona/agent/grid/ReceivedValues.scala
  src/main/scala/edu/ie3/simona/agent/grid/ReceivedValuesStore.scala
  src/main/scala/edu/ie3/simona/agent/grid/SweepValueStore.scala
  src/main/scala/edu/ie3/simona/model/grid/GridModel.scala
  src/main/scala/edu/ie3/simona/model/grid/NodeModel.scala
  src/main/scala/edu/ie3/simona/model/grid/RefSystem.scala
  src/main/scala/edu/ie3/simona/model/participant/EvcsModel.scala
  src/main/scala/edu/ie3/simona/ontology/messages/PowerMessage.scala
  src/main/scala/edu/ie3/simona/ontology/messages/VoltageMessage.scala
  src/main/scala/edu/ie3/util/scala/quantities/QuantityUtil.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmCenGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/GridAgentDataHelperSpec.scala
  src/test/scala/edu/ie3/simona/model/grid/GridSpec.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/BasicGrid.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/BasicGridWithSwitches.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/DbfsTestGrid.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/FiveLinesWithNodes.scala
  src/test/scala/edu/ie3/util/quantities/QuantityUtilSpec.scala
Labels: bug

#262 RuntimeEvent kafka sink
  CHANGELOG.md
  build.gradle
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/event/listener/DummyListener.scala
  src/main/scala/edu/ie3/simona/event/listener/RuntimeEventListener.scala
  src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventKafkaSink.scala
  src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventLogSink.scala
  src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventQueueSink.scala
  src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventSink.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerKafkaSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerSpec.scala
  src/test/scala/edu/ie3/simona/io/result/ResultEntityKafkaSpec.scala
  src/test/scala/edu/ie3/simona/test/KafkaSpecLike.scala
  src/test/scala/edu/ie3/simona/util/ConfigUtilSpec.scala
Labels: enhancement

#305 Simplifying CsvGridSource and providing TestGridFactory
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentDataHelper.scala
  src/main/scala/edu/ie3/simona/agent/grid/ReceivedValuesStore.scala
  src/main/scala/edu/ie3/simona/io/grid/CsvGridSource.scala
  src/main/scala/edu/ie3/simona/io/grid/GridProvider.scala
  src/main/scala/edu/ie3/simona/sim/setup/SetupHelper.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaSetup.scala
  src/test/groovy/edu/ie3/simona/model/participant/PVModelIT.groovy
  src/test/scala/edu/ie3/simona/sim/setup/SimonaSetupSpec.scala
  src/test/scala/edu/ie3/simona/test/common/ThreeWindingTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/GridInputTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/Transformer3wTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/TransformerInputTestData.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/DbfsTestGrid.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/TransformerTestGrid.scala
  src/test/scala/edu/ie3/simona/util/TestGridFactory.scala
Labels: dependencies, code quality
