Repository ie3-institute/simona, pull requests merged in 2022-09, with the labels that each got.

#325 Removing config of vn_146_lv_small
  CHANGELOG.md
  input/samples/vn_146_lv_small/fullGrid/line_graphic_input.csv
  input/samples/vn_146_lv_small/fullGrid/line_input.csv
  input/samples/vn_146_lv_small/fullGrid/line_type_input.csv
  input/samples/vn_146_lv_small/fullGrid/node_graphic_input.csv
  input/samples/vn_146_lv_small/fullGrid/node_input.csv
  input/samples/vn_146_lv_small/fullGrid/transformer_2_w_input.csv
  input/samples/vn_146_lv_small/fullGrid/transformer_2_w_type_input.csv
  input/samples/vn_146_lv_small/vn_146_lv_small.conf
Labels: bug

#284 Introducing faster data structures to `SimScheduler`
  CHANGELOG.md
  build.gradle
  src/main/scala/edu/ie3/simona/ontology/trigger/ScheduledTrigger.scala
  src/main/scala/edu/ie3/simona/scheduler/SchedulerHelper.scala
  src/main/scala/edu/ie3/simona/scheduler/SimScheduler.scala
  src/main/scala/edu/ie3/simona/scheduler/SimSchedulerStateData.scala
  src/main/scala/edu/ie3/util/scala/collection/mutable/CountingMap.scala
  src/main/scala/edu/ie3/util/scala/collection/mutable/PriorityMultiQueue.scala
  src/test/scala/edu/ie3/util/scala/collection/mutable/CountingMapSpec.scala
  src/test/scala/edu/ie3/util/scala/collection/mutable/PriorityMultiQueueSpec.scala
Labels: speed

#348 Removing codecov from pipeline
  Jenkinsfile
Labels: ci
