Repository ie3-institute/simona, pull requests merged in 2022-01, with the labels that each got.

#37 Make BaseRuntimeConfig serializable
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
Labels: bug

#60 Upgrading to Java 17
  Jenkinsfile
  build.gradle
  gradle.properties
  src/test/groovy/edu/ie3/simona/model/participant/PVModelTest.groovy
Labels: dependencies

#30 Separating free lots request from evcs power calculation
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/ValueStore.scala
  src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/EvMessage.scala
  src/main/scala/edu/ie3/simona/service/ev/ExtEvDataService.scala
  src/test/scala/edu/ie3/simona/agent/ValueStoreSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/EvcsAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/service/ev/ExtEvDataServiceSpec.scala
Labels: improvement

#96 Adapting to new simonaAPI
  src/main/scala/edu/ie3/simona/api/ExtMessageUtils.scala
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimLoader.scala
  src/test/scala/edu/ie3/simona/api/ExtSimAdapterSpec.scala
Labels: bug, dependencies

#75 Fix location of "vn_simona"
  CHANGELOG.md
  input/samples/vn_simona/fullGrid/line_input.csv
  input/samples/vn_simona/fullGrid/node_input.csv
Labels: enhancement

#112 Fix custom thread allocation in GridAgent
  src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmCenGridSpec.scala
Labels: bug, invalid
