Repository ie3-institute/simona, pull requests merged in 2023-07, with the labels that each got.

#561 fixing RefSystemTest
  CHANGELOG.md
  src/test/groovy/edu/ie3/simona/model/grid/RefSystemTest.groovy
Labels: test

#558 Handle codacy issues
  src/test/groovy/edu/ie3/simona/model/participant/BMModelTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/ChpModelTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/EvcsModelTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/FixedFeedModelTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/HpModelTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/PvModelIT.groovy
  src/test/groovy/edu/ie3/simona/model/participant/PvModelTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/SystemParticipantTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/WecModelTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/load/FixedLoadModelTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/load/ProfileLoadModelTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/load/RandomLoadModelTest.groovy
Labels: code quality

#565 Removing one-jar from dependencies
  CHANGELOG.md
  build.gradle
Labels: dependencies
