Repository ie3-institute/simona, pull requests merged in 2023-02, with the labels that each got.

#443 Update docs "getting started"
  docs/readthedocs/images/usersguide/copy-path.png
  docs/readthedocs/images/usersguide/edit-conf.png
  docs/readthedocs/images/usersguide/edit-conf2.png
  docs/readthedocs/usersguide.md
Labels: documentation

#445 Update sphinx dependencies
  CHANGELOG.md
  docs/readthedocs/conf.py
  docs/readthedocs/developersguide.md
  docs/readthedocs/models.md
  docs/readthedocs/models/bm_model.md
  docs/readthedocs/models/chp_model.md
  docs/readthedocs/models/cts_model.md
  docs/readthedocs/models/evcs_model.md
  docs/readthedocs/models/line_model.md
  docs/readthedocs/models/load_model.md
  docs/readthedocs/models/pv_model.md
  docs/readthedocs/models/reference_system.md
  docs/readthedocs/models/switch_model.md
  docs/readthedocs/models/three_winding_transformer_model.md
  docs/readthedocs/models/two_winding_transformer_model.md
  docs/readthedocs/models/wec_model.md
  docs/readthedocs/protocols.md
  docs/readthedocs/requirements.txt
  docs/readthedocs/usersguide.md
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies

#449 Add readthedocs python dependencies to dependabot.yml
  .github/dependabot.yml
  CHANGELOG.md
Labels: dependencies

#351 Fixing `ResultEventListener` exiting too early with high volumes of results
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala
  src/main/scala/edu/ie3/simona/io/result/ResultEntityCsvSink.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala
  src/test/scala/edu/ie3/simona/io/result/ResultEntityCsvSinkSpec.scala
  src/test/scala/edu/ie3/simona/io/result/ResultEntityKafkaSpec.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimFailSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SimonaSetupSpec.scala
Labels: bug

#462 Check the grid validity with PSDM validation utils
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/io/grid/CsvGridSource.scala
  src/main/scala/edu/ie3/simona/io/grid/GridProvider.scala
  src/test/groovy/edu/ie3/simona/model/participant/PvModelIT.groovy
Labels: enhancement

#199 create an about page for the documentation
  docs/readthedocs/about.md
  docs/readthedocs/images/usersguide/agent_messages.png
  docs/readthedocs/images/usersguide/basic_simona_environment.png
Labels: documentation

#453 Enhancing dev's guide, updating CONTRIBUTING.md
  .readthedocs.yaml
  CHANGELOG.md
  CONTRIBUTING.md
  docs/readthedocs/conf.py
  docs/readthedocs/developersguide.md
Labels: documentation

#422 Making additionalActivationTicks a SortedSet for speedier execution
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/fixedfeedin/FixedFeedInAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/load/LoadAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/pv/PvAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/statedata/BaseStateData.scala
  src/main/scala/edu/ie3/simona/agent/participant/wec/WecAgentFundamentals.scala
  src/test/scala/edu/ie3/simona/agent/participant/EvcsAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/FixedFeedInAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentFixedModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentProfileModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentExternalSourceSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentalsSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentMock.scala
  src/test/scala/edu/ie3/simona/agent/participant/PvAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/WecAgentModelCalculationSpec.scala
Labels: speed

#424 Updated csv-files according to the new syntax
  CHANGELOG.md
  input/samples/vn_simona/fullGrid/bm_input.csv
  input/samples/vn_simona/fullGrid/bm_type_input.csv
  input/samples/vn_simona/fullGrid/evcs_input.csv
  input/samples/vn_simona/fullGrid/fixed_feed_in_input.csv
  input/samples/vn_simona/fullGrid/line_graphic_input.csv
  input/samples/vn_simona/fullGrid/line_input.csv
  input/samples/vn_simona/fullGrid/line_type_input.csv
  input/samples/vn_simona/fullGrid/load_input.csv
  input/samples/vn_simona/fullGrid/measurement_unit_input.csv
  input/samples/vn_simona/fullGrid/node_graphic_input.csv
  input/samples/vn_simona/fullGrid/node_input.csv
  input/samples/vn_simona/fullGrid/pv_input.csv
  input/samples/vn_simona/fullGrid/storage_input.csv
  input/samples/vn_simona/fullGrid/storage_type_input.csv
  input/samples/vn_simona/fullGrid/transformer_2_w_input.csv
  input/samples/vn_simona/fullGrid/transformer_2_w_type_input.csv
  input/samples/vn_simona/fullGrid/wec_input.csv
  input/samples/vn_simona/fullGrid/wec_type_input.csv
Labels: format
