Repository ie3-institute/simona, pull requests merged in 2023-04, with the labels that each got.

#64 Fix three winding transformer calculation
  .scalafmt.conf
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridResultsSupport.scala
  src/main/scala/edu/ie3/simona/model/grid/Transformer3wModel.scala
  src/test/scala/edu/ie3/simona/agent/grid/GridResultsSupportSpec.scala
  src/test/scala/edu/ie3/simona/model/grid/Transformer3wModelSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/Transformer3wTestData.scala
Labels: bug

#485 Fuse switch nodes of closed switches in pf calculation
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/PowerFlowSupport.scala
  src/main/scala/edu/ie3/simona/model/grid/GridModel.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmCenGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/GridResultsSupportSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/PowerFlowSupportSpec.scala
  src/test/scala/edu/ie3/simona/model/grid/GridSpec.scala
  src/test/scala/edu/ie3/simona/model/grid/LineSpec.scala
  src/test/scala/edu/ie3/simona/test/common/UnitSpec.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/BasicGrid.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/BasicGridWithSwitches.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/DbfsTestGrid.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/FiveLinesWithNodes.scala
Labels: enhancement

#504 Fix broken style of references
  CHANGELOG.md
  docs/readthedocs/requirements.txt
Labels: documentation
