Repository ie3-institute/simona, pull requests merged in 2023-11, with the labels that each got.

#639 Small improvements to PvModel
  src/main/scala/edu/ie3/simona/model/participant/PvModel.scala
  src/test/groovy/edu/ie3/simona/model/participant/PvModelIT.groovy
  src/test/groovy/edu/ie3/simona/model/participant/PvModelTest.groovy
Labels: code quality

#649 Update gradle to v8.4
  CHANGELOG.md
  build.gradle
  gradle/scripts/documentation.gradle
  gradle/scripts/spotless.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#362 Re-implementing ``ResultEventListener`` in akka typed
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/event/ResultEvent.scala
  src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala
  src/main/scala/edu/ie3/simona/ontology/messages/StopMessage.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala
  src/test/scala/edu/ie3/simona/io/result/ResultEntityKafkaSpec.scala
Labels: akka typed

#591 Include additional test references for PvModel
  CHANGELOG.md
  src/test/groovy/edu/ie3/simona/model/participant/PvModelTest.groovy
Labels: test

#654 Introducing schedule lock
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/ontology/messages/SchedulerMessage.scala
  src/main/scala/edu/ie3/simona/scheduler/ScheduleLock.scala
  src/main/scala/edu/ie3/simona/scheduler/Scheduler.scala
  src/main/scala/edu/ie3/simona/scheduler/TimeAdvancer.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmParticipantSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala
  src/test/scala/edu/ie3/simona/scheduler/ScheduleLockIT.scala
  src/test/scala/edu/ie3/simona/scheduler/ScheduleLockSpec.scala
  src/test/scala/edu/ie3/simona/scheduler/SchedulerSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySpec.scala
  src/test/scala/edu/ie3/simona/test/common/TestSpawnerTyped.scala
Labels: enhancement

#673 Fix dev CI (removed plugin)
  Jenkinsfile
Labels: ci

#664 removed the "2.0" from the SIMONA logo
  src/main/scala/edu/ie3/simona/main/RunSimona.scala
Labels: good first issue

#571 Fix rendering of references in rtd
  CHANGELOG.md
  docs/readthedocs/requirements.txt
Labels: documentation
