Repository ie3-institute/simona, pull requests merged in 2024-07, with the labels that each got.

#842 Fix controllingEms within buildParticipantToActorRef
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
Labels: bug

#775 Implementing StorageAgent (NEW)
  CHANGELOG.md
  docs/readthedocs/config.md
  input/samples/vn_simona/fullGrid/storage_input.csv
  input/samples/vn_simona/vn_simona.conf
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/agent/participant/storage/StorageAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/storage/StorageAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/model/participant/StorageModel.scala
  src/main/scala/edu/ie3/simona/util/ConfigUtil.scala
  src/test/groovy/edu/ie3/simona/model/participant/StorageModelTest.groovy
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/participant/StorageAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/test/common/ConfigTestData.scala
  src/test/scala/edu/ie3/simona/test/common/DefaultTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/EmInputTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/StorageInputTestData.scala
  src/test/scala/edu/ie3/simona/util/ConfigUtilSpec.scala
Labels: enhancement, em

#823 Fix simulation stopping at unhandled messages in `DBFSAlgorithm`.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
Labels: bug

#724 Refactor WeatherSource and WeatherSourceWrapper.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/service/weather/SampleWeatherSource.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherService.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSource.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSourceWrapper.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherSourceSpec.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherSourceWrapperSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/EmInputTestData.scala
Labels: code quality

#813 Fix not stopping correctly on failed power flow if configured to stop
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmFailedPowerFlowSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSMockGridAgents.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherServiceSpec.scala
  src/test/scala/edu/ie3/simona/test/common/ConfigTestData.scala
  src/test/scala/edu/ie3/simona/test/common/DefaultTestData.scala
Labels: bug

#858 Removing `pekko-connectors-csv` dependency
  CHANGELOG.md
  build.gradle
  src/main/scala/edu/ie3/simona/io/result/ResultEntityCsvSink.scala
  src/test/scala/edu/ie3/simona/io/result/ResultEntityCsvSinkSpec.scala
Labels: dependencies

#839 Rewrote RefSystemTest from groovy to scala.
  CHANGELOG.md
  src/test/groovy/edu/ie3/simona/model/grid/RefSystemTest.groovy
  src/test/scala/edu/ie3/simona/model/grid/RefSystemSpec.scala
Labels: code quality, test

#845 Write ThermalHouse results when em controlled
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/fixedfeedin/FixedFeedInAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/hp/HpAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/load/LoadAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/pv/PvAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/storage/StorageAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/wec/WecAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentMock.scala
Labels: bug

#862 Fixed FixFeedModelSpec
  CHANGELOG.md
  src/test/scala/edu/ie3/simona/model/participant/FixedFeedModelSpec.scala
Labels: bug

#773 pp/#646-convert-groovy-tests-to-scalatest
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant/WecModel.scala
  src/test/groovy/edu/ie3/simona/model/participant/WecModelTest.groovy
  src/test/scala/edu/ie3/simona/model/participant/WecModelSpec.scala
Labels: test

#831 FixedLoadModelSpec.scala-convert-groovy-to-scala
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant/load/FixedLoadModel.scala
  src/test/groovy/edu/ie3/simona/model/participant/load/FixedLoadModelTest.groovy
  src/test/scala/edu/ie3/simona/model/participant/load/FixedLoadModelSpec.scala
Labels: test

#840 Rewrote SystemComponentSpec from groovy to scala
  CHANGELOG.md
  src/test/groovy/edu/ie3/simona/model/SystemComponentTest.groovy
  src/test/scala/edu/ie3/simona/model/grid/SystemComponentSpec.scala
Labels: code quality, test

#869 Update bibliography
  CHANGELOG.md
  docs/readthedocs/_static/bibliography/bibAboutSimona.bib
Labels: documentation

#866 Converting remaining rst files to markdown.
  CHANGELOG.md
  docs/readthedocs/conf.py
  docs/readthedocs/index.md
  docs/readthedocs/references.md
Labels: documentation
