Repository ie3-institute/simona, pull requests merged in 2024-02, with the labels that each got.

#710 Fixing duration calculation in result events
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/scheduler/RuntimeNotifier.scala
  src/test/scala/edu/ie3/simona/scheduler/TimeAdvancerSpec.scala
Labels: bug

#720 Create squants scalatest matchers
  CHANGELOG.md
  src/test/scala/edu/ie3/simona/agent/grid/DBFSMockGridAgents.scala
  src/test/scala/edu/ie3/simona/agent/grid/GridResultsSupportSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/EvcsAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/FixedFeedInAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/HpAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentFixedModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentProfileModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentExternalSourceSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentalsSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/PvAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/WecAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/model/assets/control/QControlSpec.scala
  src/test/scala/edu/ie3/simona/model/grid/LineSpec.scala
  src/test/scala/edu/ie3/simona/model/grid/NodeInputModelSpec.scala
  src/test/scala/edu/ie3/simona/model/grid/Transformer3wModelSpec.scala
  src/test/scala/edu/ie3/simona/model/grid/TransformerModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/ApparentPowerAndHeatSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/CharacteristicSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/FixedFeedInModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/HpModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/load/LoadModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/load/LoadProfileStoreSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithStorageOnlySpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSpec.scala
  src/test/scala/edu/ie3/simona/service/weather/SampleWeatherSourceSpec.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherSourceWrapperSpec.scala
  src/test/scala/edu/ie3/simona/test/common/UnitSpec.scala
  src/test/scala/edu/ie3/simona/test/matchers/SquantsMatchers.scala
  src/test/scala/edu/ie3/util/quantities/QuantityUtilSpec.scala
Labels: enhancement, test

#723 Solving some compiler warnings.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/config/ArgsParser.scala
  src/main/scala/edu/ie3/simona/io/result/ResultEntityCsvSink.scala
  src/main/scala/edu/ie3/simona/model/grid/Transformer3wModel.scala
  src/main/scala/edu/ie3/simona/model/grid/TransformerModel.scala
  src/main/scala/edu/ie3/simona/model/grid/TransformerTappingModel.scala
  src/main/scala/edu/ie3/simona/model/participant/load/random/RandomLoadParamStore.scala
  src/main/scala/edu/ie3/simona/service/weather/SampleWeatherSource.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSource.scala
  src/main/scala/edu/ie3/util/scala/DoubleUtils.scala
  src/main/scala/edu/ie3/util/scala/ReflectionTools.scala
  src/main/scala/edu/ie3/util/scala/quantities/ScalaNumberSystem.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/HpAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/model/grid/TransformerModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/HpModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/HpModelTestData.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySqlIT.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSqlIT.scala
Labels: code quality

#82 Correctly account for scaling factors in participant models
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/load/LoadAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/model/participant/ApparentPowerAndHeatParticipant.scala
  src/main/scala/edu/ie3/simona/model/participant/BMModel.scala
  src/main/scala/edu/ie3/simona/model/participant/ChpModel.scala
  src/main/scala/edu/ie3/simona/model/participant/EvcsModel.scala
  src/main/scala/edu/ie3/simona/model/participant/FixedFeedInModel.scala
  src/main/scala/edu/ie3/simona/model/participant/HpModel.scala
  src/main/scala/edu/ie3/simona/model/participant/PvModel.scala
  src/main/scala/edu/ie3/simona/model/participant/SystemParticipant.scala
  src/main/scala/edu/ie3/simona/model/participant/WecModel.scala
  src/main/scala/edu/ie3/simona/model/participant/load/FixedLoadModel.scala
  src/main/scala/edu/ie3/simona/model/participant/load/LoadModel.scala
  src/main/scala/edu/ie3/simona/model/participant/load/profile/ProfileLoadModel.scala
  src/main/scala/edu/ie3/simona/model/participant/load/random/RandomLoadModel.scala
  src/test/groovy/edu/ie3/simona/model/participant/ChpModelTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/load/ProfileLoadModelTest.groovy
  src/test/groovy/edu/ie3/simona/model/participant/load/RandomLoadModelTest.groovy
  src/test/scala/edu/ie3/simona/model/participant/load/LoadModelScalingSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/load/ProfileLoadModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/load/RandomLoadModelSpec.scala
  src/test/scala/edu/ie3/simona/test/matchers/QuantityMatchers.scala
  src/test/scala/edu/ie3/simona/test/matchers/QuantityMatchersSpec.scala
Labels: enhancement

#722 Fixing ref system voltage validation
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/grid/RefSystem.scala
  src/main/scala/edu/ie3/simona/sim/setup/SetupHelper.scala
Labels: bug, config

#699 Better improvements to `Scheduler` and its data structures
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/scheduler/Scheduler.scala
  src/main/scala/edu/ie3/simona/scheduler/core/Core.scala
  src/main/scala/edu/ie3/simona/scheduler/core/PhaseSwitchCore.scala
  src/main/scala/edu/ie3/simona/scheduler/core/RegularSchedulerCore.scala
  src/main/scala/edu/ie3/util/scala/Scope.scala
  src/test/scala/edu/ie3/simona/scheduler/PhaseSwitchSchedulerSpec.scala
  src/test/scala/edu/ie3/simona/scheduler/SchedulerSpec.scala
Labels: code quality

#739 Small improvements in ResultEventListener
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/event/listener/RuntimeEventListener.scala
  src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventKafkaSink.scala
  src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventLogSink.scala
  src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventQueueSink.scala
  src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventSink.scala
Labels: code quality

#737 Fixing unreliable `RuntimeEventListenerSpec`
  CHANGELOG.md
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerKafkaSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerSpec.scala
  src/test/scala/edu/ie3/simona/integration/RunSimonaStandaloneIT.scala
  src/test/scala/edu/ie3/simona/model/participant/load/LoadModelScalingSpec.scala
Labels: bug, test

#744 Add new quote for finishing sim
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/main/RunSimona.scala
Labels: enhancement

#748 Printing logs of failed tests
  CHANGELOG.md
  src/test/resources/logback-test.xml
  src/test/scala/edu/ie3/simona/agent/ValueStoreSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerKafkaSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerSpec.scala
  src/test/scala/edu/ie3/simona/test/common/UnitSpec.scala
Labels: test

#746 Convertig `SimonaSim` to a typed actor, improving failure handling
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/EnvironmentRefs.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/api/ExtSimAdapter.scala
  src/main/scala/edu/ie3/simona/event/ResultEvent.scala
  src/main/scala/edu/ie3/simona/event/RuntimeEvent.scala
  src/main/scala/edu/ie3/simona/event/listener/DelayedStopHelper.scala
  src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala
  src/main/scala/edu/ie3/simona/event/listener/RuntimeEventListener.scala
  src/main/scala/edu/ie3/simona/main/RunSimona.scala
  src/main/scala/edu/ie3/simona/main/RunSimonaStandalone.scala
  src/main/scala/edu/ie3/simona/ontology/messages/SchedulerMessage.scala
  src/main/scala/edu/ie3/simona/ontology/messages/StopMessage.scala
  src/main/scala/edu/ie3/simona/scheduler/Scheduler.scala
  src/main/scala/edu/ie3/simona/scheduler/TimeAdvancer.scala
  src/main/scala/edu/ie3/simona/sim/SimMessage.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmCenGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmFailedPowerFlowSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmParticipantSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/GridAgentSetup2WSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/GridAgentSetup3WSpec.scala
  src/test/scala/edu/ie3/simona/api/ExtSimAdapterSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala
  src/test/scala/edu/ie3/simona/integration/RunSimonaStandaloneIT.scala
  src/test/scala/edu/ie3/simona/scheduler/TimeAdvancerSpec.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimFailSpec.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SimonaSetupSpec.scala
Labels: bug, pekko typed

#721 Convert `GridAgent` & `DBFSAlgorithm` to pekko typed
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/actor/SimonaActorNaming.scala
  src/main/scala/edu/ie3/simona/agent/EnvironmentRefs.scala
  src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentMessage.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridEnvironment.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridResultsSupport.scala
  src/main/scala/edu/ie3/simona/agent/grid/PowerFlowSupport.scala
  src/main/scala/edu/ie3/simona/agent/grid/ReceivedValues.scala
  src/main/scala/edu/ie3/simona/agent/grid/ReceivedValuesStore.scala
  src/main/scala/edu/ie3/simona/agent/grid/VoltageMessage.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/state/GridAgentState.scala
  src/main/scala/edu/ie3/simona/event/notifier/Notifier.scala
  src/main/scala/edu/ie3/simona/ontology/messages/PowerMessage.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/main/scala/edu/ie3/simona/sim/setup/SetupHelper.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmCenGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmFailedPowerFlowSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmParticipantSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSMockGridAgents.scala
  src/test/scala/edu/ie3/simona/agent/grid/GridAgentSetup2WSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/GridAgentSetup3WSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/GridAgentSetupSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/GridResultsSupportSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/PowerFlowSupportSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/ReceivedValuesStoreSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgent2ListenerSpec.scala
  src/test/scala/edu/ie3/simona/event/NotifierSpec.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SetupHelperSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SimonaSetupSpec.scala
Labels: pekko typed
