Repository ie3-institute/simona, pull requests merged in 2024-10, with the labels that each got.

#978 Reorganizing pipeline stages
  CHANGELOG.md
  Jenkinsfile
Labels: ci

#993 Mh/#921 check window duration
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventLogSink.scala
  src/main/scala/edu/ie3/simona/scheduler/RuntimeNotifier.scala
Labels: bug, code quality

#998 Add some quote to 'printGoodbye'
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/main/RunSimona.scala
Labels: enhancement

#996 convert chp model test to scalatest remove groovy
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala
  src/test/groovy/edu/ie3/simona/model/participant/ChpModelTest.groovy
  src/test/scala/edu/ie3/simona/model/participant/ChpModelSpec.scala
Labels: code quality, test

#990 cylindrical thermal storage test convert groovy tests to scalatest remove groovy
  CHANGELOG.md
  src/test/groovy/edu/ie3/simona/model/thermal/CylindricalThermalStorageTest.groovy
  src/test/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorageSpec.scala
Labels: code quality, test

#1003 Replace mutable var in ChpModelSpec
  CHANGELOG.md
  src/test/scala/edu/ie3/simona/model/participant/ChpModelSpec.scala
Labels: code quality

#925 Fixed ThermalStorageResults having multiple entries
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/hp/HpAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
Labels: bug

#966 Transfer output file compression option into ResultEventListener
  CHANGELOG.md
  docs/readthedocs/config.md
  input/samples/vn_simona/vn_simona.conf
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala
  src/main/scala/edu/ie3/simona/io/result/ResultSinkType.scala
  src/main/scala/edu/ie3/simona/main/RunSimonaStandalone.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala
  src/test/scala/edu/ie3/simona/io/result/ResultSinkTypeSpec.scala
Labels: code quality
