Repository ie3-institute/simona, pull requests merged in 2024-12, with the labels that each got.

#1064 Removed Deployment
  CHANGELOG.md
  Jenkinsfile
Labels: ci

#1055 Fixing Deployment to Maven-Central in GitHub Actions
  .github/workflows/ci.yml
  CHANGELOG.md
  build.gradle
  gradle/scripts/branchName.gradle
  gradle/scripts/mavenCentralPublish.gradle
  gradle/scripts/semVer.gradle
Labels: bug, ci

#1046 chpmodelspec and cylindricalthermalstoragespec without storagevolumelvlmin
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/thermal/MutableStorage.scala
  src/test/scala/edu/ie3/simona/model/participant/ChpModelSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorageSpec.scala
Labels: code quality, test

#1066 Using the right Link for Sonar
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: ci

#1073 Fixing SonarQube QG
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: bug, ci
