Repository ie3-institute/simona, pull requests merged in 2024-09, with the labels that each got.

#946 Enabling EmAgents to handle initialization
  CHANGELOG.md
  docs/uml/protocol/em/ControlledEm.puml
  docs/uml/protocol/em/UncontrolledEm.puml
  src/main/scala/edu/ie3/simona/agent/em/EmAgent.scala
  src/main/scala/edu/ie3/simona/agent/em/EmDataCore.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/ontology/messages/flex/FlexibilityMessage.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/EvcsAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/StorageAgentModelCalculationSpec.scala
Labels: enhancement

#948 Refactoring EM messages
  CHANGELOG.md
  docs/readthedocs/models/em.md
  docs/uml/protocol/em/ControlledEm.puml
  docs/uml/protocol/em/UncontrolledEm.puml
  src/main/scala/edu/ie3/simona/agent/em/EmAgent.scala
  src/main/scala/edu/ie3/simona/agent/em/EmDataCore.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/ontology/messages/flex/FlexibilityMessage.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/EvcsAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/StorageAgentModelCalculationSpec.scala
Labels: code quality, em

#956 Fix expected secondaryData in baseStateData
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
Labels: bug

#952 Simplified methods to values in ThermalHouse
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
  src/main/scala/edu/ie3/util/scala/quantities/ThermalConductance.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseSpec.scala
  src/test/scala/edu/ie3/util/quantities/ThermalConductanceSpec.scala
Labels: code quality

#895 Prepare ThermalStorageTestData for Storage without storageVolumeLvlMin
  CHANGELOG.md
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithStorageOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalStorageTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/HpInputTestData.scala
Labels: test

#958 improve code quality in fixedloadmodelspec and other tests
  CHANGELOG.md
  src/test/scala/edu/ie3/simona/model/grid/SystemComponentSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/WecModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/load/FixedLoadModelSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseSpec.scala
Labels: code quality

#963 Fixed random failling power flow with em agents
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
Labels: bug

#885 Provide option to directly zip the output files
  CHANGELOG.md
  docs/readthedocs/config.md
  input/samples/vn_simona/vn_simona.conf
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/io/result/ResultSinkType.scala
  src/main/scala/edu/ie3/simona/main/RunSimonaStandalone.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/io/result/ResultSinkTypeSpec.scala
Labels: enhancement

#968 WeatherData HowTo for SIMONA with Copernicus ERA5 data at SIMONA RTD
  CHANGELOG.md
  docs/readthedocs/_static/bibliography/bibtexAll.bib
  docs/readthedocs/howto/weatherDataHowToCopernicusERA5.md
  docs/readthedocs/usersguide.md
Labels: documentation

#788 Fix scheduling at evcs with more than one ev at a time without em
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/model/participant/evcs/EvcsModel.scala
  src/test/scala/edu/ie3/simona/agent/participant/EvcsAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/test/common/EvTestData.scala
Labels: bug

#974 Simplifying integration in QuantityUtil, fixing test
  CHANGELOG.md
  src/main/scala/edu/ie3/util/scala/quantities/QuantityUtil.scala
  src/test/scala/edu/ie3/util/quantities/QuantityUtilSpec.scala
Labels: code quality, speed
