Repository ie3-institute/simona, pull requests merged in 2024-04, with the labels that each got.

#779 Refactoring of `GridAgent` messages.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentMessage.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentMessages.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridEnvironment.scala
  src/main/scala/edu/ie3/simona/agent/grid/PowerFlowSupport.scala
  src/main/scala/edu/ie3/simona/agent/grid/ReceivedValues.scala
  src/main/scala/edu/ie3/simona/agent/grid/ReceivedValuesStore.scala
  src/main/scala/edu/ie3/simona/agent/grid/VoltageMessage.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/ontology/messages/PowerMessage.scala
  src/main/scala/edu/ie3/simona/sim/setup/SetupHelper.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmCenGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmFailedPowerFlowSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmParticipantSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSMockGridAgents.scala
  src/test/scala/edu/ie3/simona/agent/grid/PowerFlowSupportSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/ReceivedValuesStoreSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/EvcsAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/FixedFeedInAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/HpAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentFixedModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentProfileModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgent2ListenerSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentExternalSourceSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/PvAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/WecAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SetupHelperSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SimonaSetupSpec.scala
Labels: enhancement, code quality

#726 Sh/#646 rewrite groovy test to scala test
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant/PvModel.scala
  src/test/groovy/edu/ie3/simona/model/participant/PvModelTest.groovy
  src/test/scala/edu/ie3/simona/model/participant/PvModelSpec.scala
Labels: test

#780 Making passing of `RefSystem` via config optional.
  CHANGELOG.md
  docs/readthedocs/config.md
  docs/readthedocs/models/reference_system.md
  input/samples/vn_simona/vn_simona.conf
  src/main/scala/edu/ie3/simona/config/RefSystemParser.scala
  src/main/scala/edu/ie3/simona/config/VoltLvlParser.scala
  src/test/scala/edu/ie3/simona/config/RefSystemParserSpec.scala
Labels: enhancement

#768 Correct time pattern hint
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
Labels: code quality
