Repository ie3-institute/simona, pull requests merged in 2024-11, with the labels that each got.

#1009 Fix filter for thermal result checking for lastTick not for currentTick
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/hp/HpAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/model/participant/HpModel.scala
  src/test/scala/edu/ie3/simona/agent/participant/HpAgentModelCalculationSpec.scala
Labels: bug

#1005 convert storagemodeltest to scalatest remove groovy
  CHANGELOG.md
  src/test/groovy/edu/ie3/simona/model/participant/StorageModelTest.groovy
  src/test/scala/edu/ie3/simona/model/participant/StorageModelSpec.scala
Labels: code quality, test

#985 Mh/#898 updating diagram
  CHANGELOG.md
  docs/uml/main/ExtEvSimulationClasses.puml
Labels: documentation

#1015 Fixing `CHANGELOG` entry for issue 103.
  CHANGELOG.md
Labels: documentation

#935 Add unapply method for ThermalHouseResults
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/event/ResultEvent.scala
Labels: bug, enhancement

#1024 Use zeroKW and zeroKWH in thermal grid unit tests
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant/ChpModel.scala
  src/main/scala/edu/ie3/simona/model/participant/HpModel.scala
  src/main/scala/edu/ie3/simona/model/participant/StorageModel.scala
  src/main/scala/edu/ie3/simona/model/participant/evcs/EvcsModel.scala
  src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
  src/main/scala/edu/ie3/util/scala/quantities/DefaultQuantities.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithStorageOnlySpec.scala
Labels: code quality

#982 Implementing GitHub Actions Pipeline
  .github/workflows/ci.yml
  gradle/scripts/sonarqube.gradle
Labels: ci

#1028 Removing pmd
  Jenkinsfile
  build.gradle
  gradle/scripts/pmd.gradle
Labels: dependencies

#1020 Fix some minor issues and findings from inspections
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridResultsSupport.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/load/LoadAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/statedata/ParticipantStateData.scala
  src/main/scala/edu/ie3/simona/config/ArgsParser.scala
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/model/grid/LineModel.scala
  src/main/scala/edu/ie3/simona/model/grid/TransformerTapping.scala
  src/main/scala/edu/ie3/simona/model/participant/evcs/EvcsModel.scala
  src/main/scala/edu/ie3/simona/service/weather/SampleWeatherSource.scala
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimLoader.scala
  src/main/scala/edu/ie3/simona/sim/setup/SetupHelper.scala
  src/main/scala/edu/ie3/simona/util/CollectionUtils.scala
  src/main/scala/edu/ie3/simona/util/ResultFileHierarchy.scala
  src/test/scala/edu/ie3/simona/agent/grid/GridAgentDataHelperSpec.scala
  src/test/scala/edu/ie3/simona/model/grid/GridSpec.scala
Labels: code quality

#1016 Fix initialisation freezing on empty primary data.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSpec.scala
Labels: bug

#1032 Refactoring ResultFileHierarchy
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/event/listener/ResultEventListener.scala
  src/main/scala/edu/ie3/simona/logging/logback/LogbackConfiguration.scala
  src/main/scala/edu/ie3/simona/main/RunSimona.scala
  src/main/scala/edu/ie3/simona/sim/setup/SetupHelper.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/main/scala/edu/ie3/simona/util/ResultFileHierarchy.scala
  src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala
  src/test/scala/edu/ie3/simona/integration/RunSimonaStandaloneIT.scala
  src/test/scala/edu/ie3/simona/io/file/ResultFileHierarchySpec.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SimonaSetupSpec.scala
Labels: code quality

#1045 GHA: fetch depth
  .github/workflows/ci.yml
  CHANGELOG.md
Labels: bug, ci

#1044 Fix implausible test cases of HpModelSpec
  CHANGELOG.md
  src/test/scala/edu/ie3/simona/model/participant/HpModelSpec.scala
Labels: bug, test

#1047 Correcting wrong use of "wall clock time"
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridResultsSupport.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/hp/HpAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/statedata/BaseStateData.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceProxy.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
  src/main/scala/edu/ie3/simona/service/weather/SampleWeatherSource.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentMock.scala
Labels: bug, documentation

#1048 Updating config documentation
  CHANGELOG.md
  docs/readthedocs/config.md
Labels: bug, documentation

#1011 GitHub Actions Naming Scheme
  .github/workflows/ci.yml
  build.gradle
  gradle/scripts/branchName.gradle
Labels: enhancement, ci

#1053 Refactoring to only use 'lastHpState' and 'relevantData' for 'Thermal…
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant/HpModel.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithStorageOnlySpec.scala
Labels: code quality

#1050 Introduce ThermalDemandWrapper
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant/HpModel.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridTestData.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithStorageOnlySpec.scala
Labels: code quality

#1052 Refactor thermal calcRelevantData
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant/HpModel.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithStorageOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseSpec.scala
Labels: code quality
