Repository ie3-institute/simona, pull requests merged in 2024-08, with the labels that each got.

#871 Merging both `FixedFeedInModelSpec` tests.
  CHANGELOG.md
  src/test/scala/edu/ie3/simona/model/participant/FixedFeedInModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/FixedFeedModelSpec.scala
Labels: code quality

#875 Fixing duration calculation in result events.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventLogSink.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerLoggingSpec.scala
Labels: bug

#893 ExtEvDataService returns dummy prices on request
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/service/ev/ExtEvDataService.scala
  src/test/scala/edu/ie3/simona/service/ev/ExtEvDataServiceSpec.scala
Labels: bug, enhancement

#891 Add gradle run capability
  CHANGELOG.md
  build.gradle
Labels: config

#889 Updated dependabot reviewers
  .github/dependabot.yml
  CHANGELOG.md
Labels: ci

#877 Rewrote ThermalHouseTest from groovy to scala
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
  src/test/groovy/edu/ie3/simona/model/thermal/ThermalHouseTest.groovy
  src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/HpInputTestData.scala
Labels: code quality, test

#881 Harmonised both methods that check the inner temperature of thermal house
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
Labels: code quality

#523 Changed implementation of actor naming
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/actor/SimonaActorNaming.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
Labels: enhancement

#848 Support multiple closed switches
  .gitignore
  src/main/scala/edu/ie3/simona/model/grid/GridModel.scala
  src/test/scala/edu/ie3/simona/model/grid/GridSpec.scala
Labels: enhancement

#902 Converting all instances of `eval-rst` to the equivalent myst syntax
  CHANGELOG.md
  docs/readthedocs/index.md
  docs/readthedocs/models/cts_model.md
  docs/readthedocs/models/pv_model.md
  docs/readthedocs/models/reference_system.md
  docs/readthedocs/models/three_winding_transformer_model.md
  docs/readthedocs/references.md
Labels: documentation, code quality

#777 External simulation: Providing information about next tick of MobSim
  CHANGELOG.md
  build.gradle
  docs/uml/main/ExtEvSimulationClasses.puml
  docs/uml/protocol/ExtEvSimulationSequence.puml
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/ServiceRegistration.scala
  src/main/scala/edu/ie3/simona/agent/participant/data/secondary/SecondaryDataService.scala
  src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/EvMessage.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/PrimaryDataMessage.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/ServiceMessage.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/WeatherMessage.scala
  src/main/scala/edu/ie3/simona/scheduler/core/PhaseSwitchCore.scala
  src/main/scala/edu/ie3/simona/service/ev/ExtEvDataService.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimSetupData.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/main/scala/edu/ie3/util/scala/collection/immutable/PrioritySwitchBiSet.scala
  src/test/scala/edu/ie3/simona/agent/participant/EvcsAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/scheduler/PhaseSwitchSchedulerSpec.scala
  src/test/scala/edu/ie3/simona/service/ev/ExtEvDataServiceSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSpec.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SimonaSetupSpec.scala
  src/test/scala/edu/ie3/util/scala/collection/immutable/PrioritySwitchBiSetSpec.scala
Labels: enhancement

#906 Added Simon Hütte and Philipp Schmelter to authors
  AUTHORS.md
  CHANGELOG.md
Labels: documentation, good first issue, HiWiStart

#907 Adding Pierre Petersmeier and Marvin Heintze to Authors List
  AUTHORS.md
  CHANGELOG.md
Labels: documentation, HiWiStart

#909 Reverted workaround in spotless.gradle.
  CHANGELOG.md
  gradle/scripts/spotless.gradle
Labels: dependencies

#913 Removed the trait CylindricalStorageInputTestData.scala from src/test
  src/test/scala/edu/ie3/simona/test/common/input/CylindricalStorageInputTestData.scala
Labels: code quality, HiWiStart

#910 Updated Gradle to latest Version v.8.10
  CHANGELOG.md
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: dependencies

#825 Additional tests to check flexibility options of thermal house and storage
  CHANGELOG.md
  docs/readthedocs/models.md
  docs/readthedocs/models/thermal_grid_model.md
  docs/readthedocs/models/thermal_house_model.md
  src/test/scala/edu/ie3/simona/model/participant/HpModelSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
Labels: test

#911 bm model test convert groovy tests to scalatest remove groovy
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant/BMModel.scala
  src/test/groovy/edu/ie3/simona/model/participant/BMModelTest.groovy
  src/test/scala/edu/ie3/simona/model/participant/BMModelSpec.scala
Labels: code quality, test

#927 Fix determineState of ThermalHouse
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant/HpModel.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithStorageOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseSpec.scala
Labels: bug

#923 Fix activation of Hp when not under control of an EM
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/hp/HpAgentFundamentals.scala
Labels: bug
