Repository ie3-institute/simona, pull requests merged in 2024-06, with the labels that each got.

#836 Updating to PSDM version 5.1.0
  CHANGELOG.md
  build.gradle
  src/main/scala/edu/ie3/simona/service/weather/SampleWeatherSource.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherSourceSpec.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherSourceWrapperSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/EmInputTestData.scala
Labels: dependencies

#772 Print log directory to terminal upon simulation failure
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/main/RunSimona.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SimonaSetupSpec.scala
Labels: enhancement

#771 Removing documentation index page
  CHANGELOG.md
  docs/readthedocs/conf.py
  docs/readthedocs/index.rst
Labels: documentation
