Repository ie3-institute/simona, pull requests merged in 2025-06, with the labels that each got.

#1373 Refactoring `GridAgentBuilder`
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala
  src/test/scala/edu/ie3/simona/agent/grid/congestion/CongestionTestBaseData.scala
Labels: code quality

#1410 Updated developer's guide
  CHANGELOG.md
  docs/readthedocs/developersguide.md
Labels: documentation

#1394 Fixed bugs in congestion management.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/congestion/DCMAlgorithm.scala
  src/main/scala/edu/ie3/simona/agent/grid/congestion/data/CongestionManagementData.scala
  src/test/scala/edu/ie3/simona/agent/grid/congestion/CongestedComponentsSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/congestion/CongestionTestBaseData.scala
  src/test/scala/edu/ie3/simona/agent/grid/congestion/DCMAlgorithmSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/congestion/data/CongestionManagementDataSpec.scala
  src/test/scala/edu/ie3/simona/test/common/result/CongestedComponentsTestData.scala
Labels: bug

#1412 Simplifying ScheduleLock, removing adapter
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/scheduler/ScheduleLock.scala
  src/test/scala/edu/ie3/simona/api/ExtSimAdapterSpec.scala
  src/test/scala/edu/ie3/simona/scheduler/SchedulerSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSqlIT.scala
Labels: code quality

#1419 Added `LoadProfileService` to `ParticipantRefs` in `GridAgentBuilder`
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala
Labels: bug

#1421 Adapting ParticipantAgent to scala 3 syntax
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentInit.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantInputHandler.scala
  src/main/scala/edu/ie3/simona/model/participant/ParticipantModel.scala
  src/main/scala/edu/ie3/simona/model/participant/ParticipantModelShell.scala
  src/main/scala/edu/ie3/simona/model/participant/evcs/EvcsModel.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/agent/participant/MockParticipantModel.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentInitSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentMockFactory.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/evcs/EvcsModelIT.scala
  src/test/scala/edu/ie3/simona/model/participant/evcs/EvcsModelSpec.scala
Labels: enhancement, code quality
