Repository ie3-institute/simona, pull requests merged in 2025-03, with the labels that each got.

#1108 Prepare changes for next psdm release
  CHANGELOG.md
  build.gradle
  input/samples/vn_simona/fullGrid/load_input.csv
  src/main/scala/edu/ie3/simona/model/participant/HpModel.scala
  src/main/scala/edu/ie3/simona/model/participant/evcs/EvcsModel.scala
  src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala
  src/main/scala/edu/ie3/simona/model/thermal/RandomStorageState.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalStorage.scala
  src/test/resources/edu/ie3/simona/service/primary/_it/time_series_mapping.csv
  src/test/resources/edu/ie3/simona/service/primary/_timeseries/time_series_mapping.sql
  src/test/scala/edu/ie3/simona/model/participant/ChpModelSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithStorageOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseTestData.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalStorageTestData.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherSourceWrapperSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/EmInputTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/HpInputTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/LoadInputTestData.scala
  src/test/scala/edu/ie3/simona/test/common/model/grid/DbfsTestGridWithParticipants.scala
Labels: dependencies

#1137 Refactor external simulation setup.
  CHANGELOG.md
  docs/readthedocs/usersguide.md
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimLoader.scala
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimSetupData.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/ExtSimLoaderSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/ExtSimSetupDataSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/ExtSimSetupSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SimonaSetupSpec.scala
Labels: enhancement, code quality

#1246 Showing full stacktrace on test failure
  CHANGELOG.md
  gradle/scripts/tests.gradle
Labels: bug, ci

#1241 Mh/#1192 parameter cleanup args parser
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/config/ArgsParser.scala
Labels: code quality

#1118 Use ValidationUtils for ThermalGrids
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/io/grid/GridProvider.scala
Labels: bug

#1247 Use new tick retrieval methods from PSDM.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSourceWrapper.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherSourceWrapperSpec.scala
Labels: enhancement

#1249 Fixing copernicus.eu link in readthedocs
  CHANGELOG.md
  docs/readthedocs/howto/weatherDataHowToCopernicusERA5.md
Labels: documentation

#1166 Fix determination of qDotIntoGrid in HpModel.calcState() in case heat…
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant/HpModel.scala
Labels: bug

#1180 Refactoring input and output configs
  CHANGELOG.md
  input/samples/vn_simona/vn_simona.conf
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/config/ConfigParams.scala
  src/main/scala/edu/ie3/simona/config/InputConfig.scala
  src/main/scala/edu/ie3/simona/config/OutputConfig.scala
  src/main/scala/edu/ie3/simona/config/RuntimeConfig.scala
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/io/grid/GridProvider.scala
  src/main/scala/edu/ie3/simona/io/result/ResultSinkType.scala
  src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventKafkaSink.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceProxy.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherService.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSource.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherSourceWrapper.scala
  src/main/scala/edu/ie3/simona/sim/setup/SetupHelper.scala
  src/main/scala/edu/ie3/simona/util/ConfigUtil.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerKafkaSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerLoggingSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerSpec.scala
  src/test/scala/edu/ie3/simona/io/result/ResultSinkTypeSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySqlIT.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSqlIT.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherServiceSpec.scala
  src/test/scala/edu/ie3/simona/util/ConfigUtilSpec.scala
Labels: code quality, config

#1257 Use Math.floor when calcNextEventTick for charging entities
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant2/ChargingHelper.scala
  src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/model/participant/HpModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/StorageModelSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseSpec.scala
Labels: enhancement

#1164 Implementing Version Check Step in GHA Pipeline
  .github/workflows/ci.yml
  CHANGELOG.md
  scripts/branch_type.sh
  scripts/get_versions.sh
  scripts/run-version-check.sh
  scripts/version_check.sh
Labels: ci

#1254 Check for fully charged Evs when determine next OperationPoint of Evcs
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant2/ParticipantModelShell.scala
  src/main/scala/edu/ie3/simona/model/participant2/evcs/EvcsModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/evcs/MaximumPowerCharging.scala
  src/test/scala/edu/ie3/simona/model/participant2/evcs/EvcsModelSpec.scala
Labels: bug

#1261 Removal of Jenkinsfile
  CHANGELOG.md
  Jenkinsfile
Labels: ci

#1264 Sequential test execution
  CHANGELOG.md
  README.md
  gradle/scripts/sonarqube.gradle
  gradle/scripts/tests.gradle
  src/test/resources/application-test.conf
Labels: ci, test

#1215 Converting `ExtEvDataService` to pekko typed.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/EnvironmentRefs.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInit.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/EvMessage.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/ServiceMessage.scala
  src/main/scala/edu/ie3/simona/service/ExtDataSupport.scala
  src/main/scala/edu/ie3/simona/service/ServiceStateData.scala
  src/main/scala/edu/ie3/simona/service/TypedSimonaService.scala
  src/main/scala/edu/ie3/simona/service/ev/ExtEvDataService.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimSetupData.scala
  src/test/scala/edu/ie3/simona/model/participant2/evcs/EvcsModelIT.scala
  src/test/scala/edu/ie3/simona/model/participant2/evcs/EvcsModelSpec.scala
  src/test/scala/edu/ie3/simona/service/ev/ExtEvDataServiceSpec.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/ExtSimSetupDataSpec.scala
Labels: pekko typed

#1255 Introducing `BmModel` for the new ParticipantAgent
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant/BMModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/BmModel.scala
  src/test/scala/edu/ie3/simona/model/participant/BMModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/BmModelSpec.scala
Labels: enhancement

#1270 Gradle update to version 8.13
  CHANGELOG.md
  build.gradle
  gradle/scripts/deploy.gradle
  gradle/scripts/documentation.gradle
  gradle/scripts/mavenCentralPublish.gradle
  gradle/scripts/sonarqube.gradle
  gradle/scripts/spotless.gradle
  gradle/scripts/tests.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: dependencies

#1274 Fix bug in `ExtDataSupport.adapter`.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/ontology/messages/services/ServiceMessage.scala
  src/main/scala/edu/ie3/simona/service/ExtDataSupport.scala
Labels: bug

#1279 Removing `ChpModel`
  docs/readthedocs/models/chp_model.md
  src/main/scala/edu/ie3/simona/model/participant/ChpModel.scala
  src/main/scala/edu/ie3/simona/model/participant/HpModel.scala
  src/main/scala/edu/ie3/simona/util/ConfigUtil.scala
  src/main/scala/edu/ie3/simona/util/EntityMapperUtil.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/event/NotifierSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/ChpModelSpec.scala
  src/test/scala/edu/ie3/simona/util/ConfigUtilSpec.scala
Labels: code quality

#1278 Removing pausing/continuing functionality from TimeAdvancer
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/event/RuntimeEvent.scala
  src/main/scala/edu/ie3/simona/io/runtime/RuntimeEventLogSink.scala
  src/main/scala/edu/ie3/simona/scheduler/RuntimeNotifier.scala
  src/main/scala/edu/ie3/simona/scheduler/TimeAdvancer.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerLoggingSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerSpec.scala
  src/test/scala/edu/ie3/simona/scheduler/TimeAdvancerSpec.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
Labels: code quality

#1277 Fixing initialization scheduling by using ScheduleLocks
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInit.scala
  src/main/scala/edu/ie3/simona/scheduler/RuntimeNotifier.scala
  src/main/scala/edu/ie3/simona/scheduler/ScheduleLock.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceProxy.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/main/scala/edu/ie3/simona/util/SimonaConstants.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmCenGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmFailedPowerFlowSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmParticipantSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInitSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/evcs/EvcsModelIT.scala
  src/test/scala/edu/ie3/simona/scheduler/ScheduleLockSpec.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
Labels: bug

#1282 Remove `MutableStorage`
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala
  src/main/scala/edu/ie3/simona/model/thermal/MutableStorage.scala
  src/main/scala/edu/ie3/simona/model/thermal/MutableTemperature.scala
  src/main/scala/edu/ie3/simona/model/thermal/RandomStorageState.scala
  src/test/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorageSpec.scala
Labels: code quality

#1276 Fixing Gradle Problems
  CHANGELOG.md
  gradle/scripts/mavenCentralPublish.gradle
  gradle/scripts/tests.gradle
Labels: bug

#1287 Change logging level for unsupported messages from ExtDataSupport
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/service/ExtDataSupport.scala
  src/main/scala/edu/ie3/simona/service/TypedSimonaService.scala
Labels: log

#1291 Fixing schedule lock tick in primary service proxy
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceProxy.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySpec.scala
Labels: bug

#1290 Fixing `time_series_mapping.csv`
  CHANGELOG.md
  input/samples/vn_simona/fullGrid/time_series_mapping.csv
Labels: bug

#1294 Fix hierarchical em structures leading to exception while initializing.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala
Labels: bug

#1218 Convert `WeatherService` to typed
  .github/workflows/ci.yml
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/EnvironmentRefs.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala
  src/main/scala/edu/ie3/simona/agent/participant/ServiceRegistration.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInit.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/ServiceMessage.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/WeatherMessage.scala
  src/main/scala/edu/ie3/simona/service/TypedSimonaService.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherService.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmCenGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmFailedPowerFlowSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmParticipantSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/HpAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInitSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSpec.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherServiceSpec.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SimonaSetupSpec.scala
Labels: pekko typed

#1183 Change thermal house behaviour to heat till targetTemperature
  CHANGELOG.md
  docs/readthedocs/models/thermal_house_model.md
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/model/participant/HpModelSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalStorageTestData.scala
Labels: enhancement

#1300 Refactoring `ExtEvDataService` and fixing message handling bug
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/service/ExtDataSupport.scala
  src/main/scala/edu/ie3/simona/service/TypedSimonaService.scala
Labels: bug

#1187 Add test case to EmAgentIT to check for correct reactive power
  CHANGELOG.md
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/test/common/input/LoadInputTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/PvInputTestData.scala
Labels: test

#1231 Convert primary service to pekko typed
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInit.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/ServiceMessage.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceProxy.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/agent/participant/HpAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInitSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySqlIT.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSqlIT.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SimonaSetupSpec.scala
Labels: pekko typed

#1299 Removed untyped simona service.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/EnvironmentRefs.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInit.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantInputHandler.scala
  src/main/scala/edu/ie3/simona/io/result/plain/PlainWriter.scala
  src/main/scala/edu/ie3/simona/service/ExtDataSupport.scala
  src/main/scala/edu/ie3/simona/service/SimonaService.scala
  src/main/scala/edu/ie3/simona/service/TypedSimonaService.scala
  src/main/scala/edu/ie3/simona/service/ev/ExtEvDataService.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceProxy.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherService.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimSetupData.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmCenGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmFailedPowerFlowSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmParticipantSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/agent/participant/HpAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentMock.scala
  src/test/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInitSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant2/ParticipantAgentSpec.scala
  src/test/scala/edu/ie3/simona/model/grid/LineSpec.scala
  src/test/scala/edu/ie3/simona/model/grid/TransformerModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/PvModelITSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/evcs/EvcsModelIT.scala
  src/test/scala/edu/ie3/simona/model/participant2/evcs/EvcsModelSpec.scala
  src/test/scala/edu/ie3/simona/service/ev/ExtEvDataServiceSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySqlIT.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSqlIT.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherServiceSpec.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/ExtSimSetupDataSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SimonaSetupSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/NodeInputTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/WecInputTestData.scala
Labels: enhancement

#1304 Made some method of `PvModel` static
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant2/PvModel.scala
  src/test/scala/edu/ie3/simona/model/participant2/PvModelSpec.scala
Labels: code quality

#1303 Fixed pekko config not written as output
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/main/RunSimonaStandalone.scala
  src/main/scala/edu/ie3/simona/sim/setup/SetupHelper.scala
  src/main/scala/edu/ie3/simona/util/ResultFileHierarchy.scala
  src/test/scala/edu/ie3/simona/integration/RunSimonaStandaloneIT.scala
Labels: bug, config

#1159 ThermalGrid integration test (with Em)
  CHANGELOG.md
  docs/readthedocs/models/thermal_house_model.md
  src/main/scala/edu/ie3/simona/event/ResultEvent.scala
  src/main/scala/edu/ie3/simona/model/participant/HpModel.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridSpec.scala
Labels: test, em

#1318 Added check for equal start and end date of simulation to ConfigFailFast
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
Labels: config

#1321 Cleanups and log capturing in and adround `ExtEvDataServiceSpec`
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/service/ExtDataSupport.scala
  src/main/scala/edu/ie3/simona/service/ServiceStateData.scala
  src/main/scala/edu/ie3/simona/service/SimonaService.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
  src/test/scala/edu/ie3/simona/service/ev/ExtEvDataServiceSpec.scala
Labels: code quality
