Repository ie3-institute/simona, pull requests merged in 2025-02, with the labels that each got.

#1128 Fix negative required energy demand for thermalHouse
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
Labels: bug

#689 Some fixes in PvModel and test
  docs/readthedocs/_static/bibliography/bibtexAll.bib
  docs/readthedocs/models/pv_model.md
  src/main/scala/edu/ie3/simona/model/participant/PvModel.scala
  src/test/resources/edu/ie3/simona/model/participant/_pv/it/results.tar.gz
  src/test/resources/edu/ie3/simona/model/participant/_pv/it/results2.tar.gz
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/model/participant/PvModelITHelper.scala
  src/test/scala/edu/ie3/simona/model/participant/PvModelSpec.scala
Labels: code quality

#1139 Refactoring EM messages, fixing documentation
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/em/EmAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/ontology/messages/flex/FlexibilityMessage.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/EvcsAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/StorageAgentModelCalculationSpec.scala
Labels: code quality

#1125 Enhance exception message in case of InvalidGridException
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/grid/GridModel.scala
Labels: internal

#1141 Renaming `PrimaryDataWithApparentPower` to `PrimaryDataWithComplexPower`
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/ServiceRegistration.scala
  src/main/scala/edu/ie3/simona/agent/participant/data/Data.scala
  src/main/scala/edu/ie3/simona/agent/participant/statedata/BaseStateData.scala
  src/main/scala/edu/ie3/simona/agent/participant/statedata/DataCollectionStateData.scala
  src/main/scala/edu/ie3/simona/agent/participant/statedata/ParticipantStateData.scala
  src/main/scala/edu/ie3/simona/io/result/AccompaniedSimulationResult.scala
  src/main/scala/edu/ie3/simona/model/participant/SystemParticipant.scala
Labels: code quality

#1148 Moving `ScheduleServiceActivation` to its right place
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/api/ExtSimAdapter.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/ServiceMessage.scala
  src/main/scala/edu/ie3/simona/service/SimonaService.scala
  src/test/scala/edu/ie3/simona/api/ExtSimAdapterSpec.scala
Labels: code quality

#1147 `OperationInterval` extends `RightOpenInterval`
  CHANGELOG.md
  src/main/scala/edu/ie3/util/scala/OperationInterval.scala
Labels: bug

#1132 Enhance EmAggregate of SelfOpt to cope with other targetLimits
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/em/EmAggregatePowerOpt.scala
  src/main/scala/edu/ie3/simona/model/em/EmModelShell.scala
  src/test/scala/edu/ie3/simona/model/em/EmAggregatePowerOptSpec.scala
  src/test/scala/edu/ie3/simona/model/em/EmAggregateSelfOptSpec.scala
  src/test/scala/edu/ie3/simona/model/em/EmModelShellSpec.scala
Labels: enhancement

#879 ThermalGrid integration test (noEm)
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/HpInputTestData.scala
Labels: test, em

#1169 Switching to `pureconfig`.
  CHANGELOG.md
  build.gradle
  gradle/scripts/documentation.gradle
  gradle/scripts/tscfg.gradle
  input/samples/vn_simona/vn_simona.conf
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/main/RunSimonaStandalone.scala
  src/main/scala/edu/ie3/simona/sim/setup/SetupHelper.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/main/scala/edu/ie3/simona/util/ResultFileHierarchy.scala
  src/test/scala/edu/ie3/simona/agent/grid/GridAgentSetupSpec.scala
  src/test/scala/edu/ie3/simona/integration/RunSimonaStandaloneIT.scala
Labels: enhancement, config

#1171 Cleaning up `SimonaConfig`.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
Labels: code quality, config

#1168 Check for runningHp when handling infeed to thermalGrid
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
Labels: bug

#1177 changed pvInput values and corresponding expected results
  CHANGELOG.md
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/test/common/input/PvInputTestData.scala
Labels: code quality

#1173 Refactor `RuntimeConfig`
  CHANGELOG.md
  input/samples/vn_simona/vn_simona.conf
  src/main/resources/config/config-template.conf
  src/main/scala/edu/ie3/simona/agent/em/EmAgent.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/ServiceRegistration.scala
  src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/fixedfeedin/FixedFeedInAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/fixedfeedin/FixedFeedInAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/hp/HpAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/hp/HpAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/load/LoadAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/load/LoadAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/pv/PvAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/pv/PvAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/statedata/ParticipantStateData.scala
  src/main/scala/edu/ie3/simona/agent/participant/storage/StorageAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/storage/StorageAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/wec/WecAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/wec/WecAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/config/ArgsParser.scala
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/config/RuntimeConfig.scala
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/event/listener/RuntimeEventListener.scala
  src/main/scala/edu/ie3/simona/model/em/EmModelShell.scala
  src/main/scala/edu/ie3/simona/model/participant/FixedFeedInModel.scala
  src/main/scala/edu/ie3/simona/model/participant/load/LoadReference.scala
  src/main/scala/edu/ie3/simona/util/ConfigUtil.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/agent/participant/EvcsAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/FixedFeedInAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/HpAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentFixedModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentProfileModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgent2ListenerSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentExternalSourceSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentalsSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentMock.scala
  src/test/scala/edu/ie3/simona/agent/participant/PvAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/StorageAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/WecAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerKafkaSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerLoggingSpec.scala
  src/test/scala/edu/ie3/simona/event/listener/RuntimeEventListenerSpec.scala
  src/test/scala/edu/ie3/simona/model/em/EmModelShellSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/FixedFeedInModelSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/EmInputTestData.scala
  src/test/scala/edu/ie3/simona/util/ConfigUtilSpec.scala
Labels: code quality, config

#1198 Adapting to new `ParticipantAgent` messages
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentData.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentMessages.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridEnvironment.scala
  src/main/scala/edu/ie3/simona/agent/grid/ReceivedValuesStore.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant/data/Data.scala
  src/main/scala/edu/ie3/simona/agent/participant/evcs/EvcsAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInit.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/EvMessage.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/PrimaryDataMessage.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/ServiceMessage.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/WeatherMessage.scala
  src/main/scala/edu/ie3/simona/service/ev/ExtEvDataService.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceProxy.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceWorker.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherService.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmParticipantSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/ReceivedValuesStoreSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/agent/participant/EvcsAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/FixedFeedInAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/HpAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentFixedModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentProfileModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgent2ListenerSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentExternalSourceSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/PvAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/StorageAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/WecAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInitSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant2/ParticipantAgentSpec.scala
  src/test/scala/edu/ie3/simona/service/ev/ExtEvDataServiceSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySqlIT.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceWorkerSqlIT.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherServiceSpec.scala
Labels: enhancement

#1194 Renamed some methods and variables within `ThermalGrid` and `ThermalH…
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
  src/test/scala/edu/ie3/simona/model/participant/HpModelSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseSpec.scala
Labels: code quality

#1203 Participant now sends `FlexResult` to EM
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgent.scala
  src/test/scala/edu/ie3/simona/agent/participant2/ParticipantAgentSpec.scala
Labels: bug

#1201 Implementing result handling with `NotifierConfig` in new Participant
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInit.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantResultHandler.scala
  src/main/scala/edu/ie3/simona/model/participant2/ParticipantModelShell.scala
  src/test/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInitSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant2/ParticipantAgentMockFactory.scala
  src/test/scala/edu/ie3/simona/agent/participant2/ParticipantAgentSpec.scala
Labels: enhancement

#1068 Change Java Durations into Scala Durations
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
  src/main/scala/edu/ie3/simona/agent/grid/PowerFlowParams.scala
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/grid/PowerFlowSupportSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/agent/participant/FixedFeedInAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/HpAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentFixedModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/LoadAgentProfileModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgent2ListenerSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/ParticipantAgentExternalSourceSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/PvAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/StorageAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant/WecAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
Labels: enhancement, java

#1206 Introducing `FixedFeedInModel` for the new ParticipantAgent
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/agent/participant/fixedfeedin/FixedFeedInAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/fixedfeedin/FixedFeedInAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/model/participant/FixedFeedInModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/FixedFeedInModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/ParticipantModelInit.scala
  src/test/scala/edu/ie3/simona/agent/participant/FixedFeedInAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/FixedFeedInModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/FixedFeedInModelSpec.scala
Labels: enhancement

#1211 Remove `SimonaListener` and related code.
  CHANGELOG.md
  docs/readthedocs/config.md
  input/samples/vn_simona/vn_simona.conf
  src/main/scala/edu/ie3/simona/config/ArgsParser.scala
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/event/listener/SimonaListener.scala
  src/main/scala/edu/ie3/simona/event/listener/SimonaListenerCompanion.scala
  src/main/scala/edu/ie3/simona/event/listener/SimonaListenerWithFilter.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/main/scala/edu/ie3/util/scala/ReflectionTools.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/event/SimonaListenerSpec.scala
  src/test/scala/edu/ie3/simona/test/common/ConfigTestData.scala
Labels: code quality

#1197 Typo and format of `ThermalGrid` and `ThermalHouse` ScalaDocs
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
Labels: documentation

#1224 Setting a higher testing timefactor
  CHANGELOG.md
  src/test/resources/application-test.conf
Labels: test

#1213 Basing `PvModel` on irradiance, not irradiation
  CHANGELOG.md
  docs/readthedocs/models/pv_model.md
  src/main/scala/edu/ie3/simona/agent/participant/pv/PvAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/model/participant/PvModel.scala
  src/main/scala/edu/ie3/simona/service/weather/WeatherService.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/model/participant/PvModelITSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/PvModelSpec.scala
Labels: bug, enhancement

#1226 Introducing `WecModel` for the new ParticipantAgent
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/agent/participant/wec/WecAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/wec/WecAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/model/participant/WecModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/ParticipantModelInit.scala
  src/main/scala/edu/ie3/simona/model/participant2/WecModel.scala
  src/test/scala/edu/ie3/simona/agent/participant/WecAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/WecModelSpec.scala
Labels: enhancement

#1227 Introducing `StorageModel` for the new ParticipantAgent
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentController.scala
  src/main/scala/edu/ie3/simona/agent/participant/storage/StorageAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/storage/StorageAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/model/participant/StorageModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/ChargingHelper.scala
  src/main/scala/edu/ie3/simona/model/participant2/ParticipantModelInit.scala
  src/main/scala/edu/ie3/simona/model/participant2/StorageModel.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/participant/StorageAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/ChargingHelperSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/StorageModelSpec.scala
Labels: enhancement

#1238 Improving and fixing input data provision in `ParticipantModel`
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantInputHandler.scala
  src/main/scala/edu/ie3/simona/model/participant2/ParticipantModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/PrimaryDataParticipantModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/PvModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/WecModel.scala
  src/test/scala/edu/ie3/simona/agent/participant2/MockParticipantModel.scala
Labels: bug
