Repository ie3-institute/simona, pull requests merged in 2025-01, with the labels that each got.

#1098 Throw exception if the slack node is not directly conected to a transformer.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/io/grid/GridProvider.scala
Labels: bug, enhancement

#1104 Added support for topologies without transformers and slack grids with multiple nodes
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/DBFSAlgorithm.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgent.scala
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentMessages.scala
  src/main/scala/edu/ie3/simona/agent/grid/PowerFlowSupport.scala
  src/main/scala/edu/ie3/simona/io/grid/GridProvider.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSMockGridAgents.scala
  src/test/scala/edu/ie3/simona/agent/grid/PowerFlowSupportSpec.scala
Labels: enhancement

#1113 Sending flex options even if not em-controlled
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/em/EmAgent.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentSpec.scala
Labels: bug

#1123 Checking the number of slack nodes.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/io/grid/GridProvider.scala
Labels: enhancement

#918 Refactor ThermalEnergyDemand
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridSpec.scala
Labels: enhancement, HiWiStart

#1089 pv model it convert groovy tests to scalatest
  CHANGELOG.md
  Jenkinsfile
  build.gradle
  gradle/scripts/sonarqube.gradle
  gradle/scripts/spotless.gradle
  gradle/scripts/tests.gradle
  src/test/groovy/edu/ie3/simona/model/participant/PvModelIT.groovy
  src/test/resources/SpockConfig.groovy
  src/test/resources/edu/ie3/simona/model/participant/_pv/it/grid_data/node_input.csv
  src/test/resources/edu/ie3/simona/model/participant/_pv/it/grid_data/pv_input.csv
  src/test/scala/edu/ie3/simona/model/participant/PvModelITHelper.scala
  src/test/scala/edu/ie3/simona/model/participant/PvModelITSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/NodeInputTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/PvInputTestData.scala
Labels: code quality, test
