Repository ie3-institute/simona, pull requests merged in 2025-05, with the labels that each got.

#1365 Added configuration for console log level.
  CHANGELOG.md
  docs/readthedocs/config.md
  input/samples/vn_simona/vn_simona.conf
  src/main/resources/logback.xml
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/config/OutputConfig.scala
  src/main/scala/edu/ie3/simona/logging/logback/LogbackConfiguration.scala
  src/main/scala/edu/ie3/simona/sim/setup/SetupHelper.scala
  src/test/scala/edu/ie3/simona/event/listener/ResultEventListenerSpec.scala
  src/test/scala/edu/ie3/simona/integration/RunSimonaStandaloneIT.scala
  src/test/scala/edu/ie3/simona/io/file/ResultFileHierarchySpec.scala
  src/test/scala/edu/ie3/simona/io/result/ResultEntityKafkaSpec.scala
Labels: enhancement

#1360 Factory case class in BmModel and BmInput case in GridAgentBuilder
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala
  src/main/scala/edu/ie3/simona/config/RuntimeConfig.scala
  src/main/scala/edu/ie3/simona/model/participant/BmModel.scala
  src/main/scala/edu/ie3/simona/model/participant/ParticipantModelInit.scala
  src/main/scala/edu/ie3/simona/util/ConfigUtil.scala
  src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala
  src/test/scala/edu/ie3/simona/model/participant/BmModelSpec.scala
  src/test/scala/edu/ie3/simona/util/ConfigUtilSpec.scala
Labels: enhancement

#1366 Making primary data source optional.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/service/primary/PrimaryServiceProxy.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
  src/test/scala/edu/ie3/simona/service/primary/PrimaryServiceProxySpec.scala
Labels: enhancement, config

#1337 Refactoring uuids in default runtime configs.
  CHANGELOG.md
  docs/readthedocs/config.md
  src/main/scala/edu/ie3/simona/config/ConfigFailFast.scala
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/test/scala/edu/ie3/simona/config/ConfigFailFastSpec.scala
Labels: enhancement, code quality

#1357 Added load profile service.
  CHANGELOG.md
  build.gradle
  src/main/resources/load/random_load_parameters.csv
  src/main/resources/load/standard_load_profiles.csv
  src/main/scala/edu/ie3/simona/agent/EnvironmentRefs.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/ParticipantAgentInit.scala
  src/main/scala/edu/ie3/simona/config/InputConfig.scala
  src/main/scala/edu/ie3/simona/model/participant/ParticipantModel.scala
  src/main/scala/edu/ie3/simona/model/participant/load/DayType.scala
  src/main/scala/edu/ie3/simona/model/participant/load/FixedLoadModel.scala
  src/main/scala/edu/ie3/simona/model/participant/load/LoadModel.scala
  src/main/scala/edu/ie3/simona/model/participant/load/ProfileLoadModel.scala
  src/main/scala/edu/ie3/simona/model/participant/load/profile/LoadProfileKey.scala
  src/main/scala/edu/ie3/simona/model/participant/load/profile/LoadProfileStore.scala
  src/main/scala/edu/ie3/simona/model/participant/load/profile/ProfileLoadModel.scala
  src/main/scala/edu/ie3/simona/model/participant/load/profile/Season.scala
  src/main/scala/edu/ie3/simona/model/participant/load/profile/TypeDayProfile.scala
  src/main/scala/edu/ie3/simona/model/participant/load/random/RandomLoadModel.scala
  src/main/scala/edu/ie3/simona/model/participant/load/random/RandomLoadParamStore.scala
  src/main/scala/edu/ie3/simona/model/participant/load/random/RandomLoadParameters.scala
  src/main/scala/edu/ie3/simona/model/participant/load/random/TypeDayParameters.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/LoadProfileMessage.scala
  src/main/scala/edu/ie3/simona/ontology/messages/services/ServiceMessage.scala
  src/main/scala/edu/ie3/simona/service/ServiceType.scala
  src/main/scala/edu/ie3/simona/service/load/LoadProfileService.scala
  src/main/scala/edu/ie3/simona/service/load/LoadProfileSources.scala
  src/main/scala/edu/ie3/simona/service/load/LoadProfileStore.scala
  src/main/scala/edu/ie3/simona/sim/SimonaSim.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/SimonaStandaloneSetup.scala
  src/test/resources/edu/ie3/simona/model/participant/load/profile/standard_load_profiles_test.csv
  src/test/resources/edu/ie3/simona/model/participant/load/random/random_load_parameters_test.csv
  src/test/resources/edu/ie3/simona/service/load/_it/lpts_g0.csv
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmCenGridSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmFailedPowerFlowSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmParticipantSpec.scala
  src/test/scala/edu/ie3/simona/agent/grid/DBFSAlgorithmSupGridSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/load/FixedLoadModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/load/LoadModelTestHelper.scala
  src/test/scala/edu/ie3/simona/model/participant/load/ProfileLoadModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/load/profile/LoadProfileStoreSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/load/profile/TypeDayProfileSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/load/random/RandomLoadModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/load/random/RandomLoadParamStoreSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/load/random/TypeDayParametersSpec.scala
  src/test/scala/edu/ie3/simona/service/load/LoadProfileServiceSpec.scala
  src/test/scala/edu/ie3/simona/service/load/LoadProfileSourcesSpec.scala
  src/test/scala/edu/ie3/simona/service/load/LoadProfileStoreSpec.scala
  src/test/scala/edu/ie3/simona/service/weather/WeatherServiceSpec.scala
  src/test/scala/edu/ie3/simona/sim/SimonaSimSpec.scala
  src/test/scala/edu/ie3/simona/sim/setup/SimonaSetupSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/LoadInputTestData.scala
Labels: enhancement

#1388 Added CODEOWNERS file
  .github/CODEOWNERS
  .github/dependabot.yml
  CHANGELOG.md
Labels: dependencies, ci

#1399 Fixes in Documentation, ScalaDocs, Code Style
  CHANGELOG.md
  docs/readthedocs/models/cts_model.md
  src/main/scala/edu/ie3/simona/model/participant/HpModel.scala
  src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridTestData.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithStorageOnlySpec.scala
  src/test/scala/edu/ie3/util/quantities/QuantityConversionUtilsSpec.scala
Labels: code quality
