Repository ie3-institute/simona, pull requests merged in 2025-04, with the labels that each got.

#1328 Isolating solar radiation functionality to its own object
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant2/PvModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/SolarIrradiationCalculation.scala
  src/test/scala/edu/ie3/simona/model/participant2/PvModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/SolarIrradiationCalculationSpec.scala
Labels: code quality

#1325 Introducing participant model factory pattern
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInit.scala
  src/main/scala/edu/ie3/simona/model/participant2/BmModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/FixedFeedInModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/ParticipantModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/ParticipantModelInit.scala
  src/main/scala/edu/ie3/simona/model/participant2/ParticipantModelShell.scala
  src/main/scala/edu/ie3/simona/model/participant2/PrimaryDataParticipantModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/PvModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/StorageModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/WecModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/evcs/EvcsModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/load/FixedLoadModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/load/LoadModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/load/profile/ProfileLoadModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/load/random/RandomLoadModel.scala
  src/test/scala/edu/ie3/simona/agent/participant2/MockParticipantModel.scala
  src/test/scala/edu/ie3/simona/agent/participant2/ParticipantAgentInitSpec.scala
  src/test/scala/edu/ie3/simona/agent/participant2/ParticipantAgentSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/FixedFeedInModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/PvModelITHelper.scala
  src/test/scala/edu/ie3/simona/model/participant2/PvModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/StorageModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/WecModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/evcs/EvcsModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/load/FixedLoadModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/load/profile/ProfileLoadModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/load/random/RandomLoadModelSpec.scala
Labels: enhancement

#1236 Introducing HpModel for the new ParticipantAgent
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/grid/GridAgentBuilder.scala
  src/main/scala/edu/ie3/simona/agent/participant/hp/HpAgent.scala
  src/main/scala/edu/ie3/simona/agent/participant/hp/HpAgentFundamentals.scala
  src/main/scala/edu/ie3/simona/agent/participant2/ParticipantResultHandler.scala
  src/main/scala/edu/ie3/simona/model/participant/HpModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/HpModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/ParticipantModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/ParticipantModelInit.scala
  src/main/scala/edu/ie3/simona/model/participant2/ParticipantModelShell.scala
  src/main/scala/edu/ie3/simona/model/participant2/PrimaryDataParticipantModel.scala
  src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalStorage.scala
  src/main/scala/edu/ie3/util/scala/quantities/DefaultQuantities.scala
  src/test/scala/edu/ie3/simona/agent/em/EmAgentIT.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/agent/participant/HpAgentModelCalculationSpec.scala
  src/test/scala/edu/ie3/simona/model/participant/HpModelSpec.scala
  src/test/scala/edu/ie3/simona/model/participant2/HpModelSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridTestData.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithStorageOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseSpec.scala
  src/test/scala/edu/ie3/simona/test/common/input/EmInputTestData.scala
  src/test/scala/edu/ie3/simona/test/common/input/HpInputTestData.scala
Labels: enhancement

#1323 Fix determining FlexOptions of Evcs
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant2/evcs/EvcsModel.scala
  src/test/scala/edu/ie3/simona/model/participant2/evcs/EvcsModelSpec.scala
Labels: bug

#1316 Add conversion utils between `ComparableQuantity` and `Squants`.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/agent/em/EmAgent.scala
  src/main/scala/edu/ie3/simona/model/grid/LineModel.scala
  src/main/scala/edu/ie3/simona/model/grid/NodeModel.scala
  src/main/scala/edu/ie3/simona/model/grid/Transformer3wModel.scala
  src/main/scala/edu/ie3/simona/model/grid/TransformerModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/FixedFeedInModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/HpModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/PvModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/StorageModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/WecModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/evcs/EvModelWrapper.scala
  src/main/scala/edu/ie3/simona/model/participant2/evcs/EvcsModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/load/FixedLoadModel.scala
  src/main/scala/edu/ie3/simona/model/participant2/load/LoadModel.scala
  src/main/scala/edu/ie3/util/scala/quantities/ApparentPower.scala
  src/main/scala/edu/ie3/util/scala/quantities/QuantityConversionUtils.scala
Labels: enhancement, code quality

#1340 Implemented auto-merge
  .github/workflows/dependabot-auto-merge.yml
  CHANGELOG.md
Labels: ci

#1343 Refactor handleFeedIn and handleConsumption of thermalGrid due to qDo…
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/participant2/HpModel.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalGrid.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithStorageOnlySpec.scala
Labels: code quality

#1346 Fix tolerance in ThermalGridIT
  CHANGELOG.md
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
Labels: bug

#1348 Fix startingState of ThermalHouse and ThermalStorage
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/model/thermal/CylindricalThermalStorage.scala
  src/main/scala/edu/ie3/simona/model/thermal/ThermalHouse.scala
  src/test/scala/edu/ie3/simona/agent/grid/ThermalGridIT.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseAndStorageSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalGridWithHouseOnlySpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseSpec.scala
  src/test/scala/edu/ie3/simona/model/thermal/ThermalHouseTestData.scala
Labels: bug

#1312 Adapted to typed actor in simonaAPI
  CHANGELOG.md
  build.gradle
  src/main/scala/edu/ie3/simona/api/ExtSimAdapter.scala
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimSetup.scala
  src/main/scala/edu/ie3/simona/sim/setup/ExtSimSetupData.scala
  src/test/scala/edu/ie3/simona/api/ExtSimAdapterSpec.scala
  src/test/scala/edu/ie3/simona/service/ev/ExtEvDataServiceSpec.scala
Labels: enhancement

#1356 Fixing default config values not written to output config file.
  CHANGELOG.md
  src/main/scala/edu/ie3/simona/config/SimonaConfig.scala
  src/main/scala/edu/ie3/simona/util/ResultFileHierarchy.scala
Labels: bug

#1354 Auto Review and update Restriction for SNAPSHOTS
  .github/workflows/dependabot-auto-merge.yml
  CHANGELOG.md
Labels: bug, dependencies, ci
